### PR TITLE
Added fix for untracked single profile accounts.

### PR DESCRIPTION
**Pull request by ghost**
Fix was done by setting a default name for the first profile an account logs onto. This default name
is then replaced with the profiles actual name when the account switches to it. 

There also seemed to be another small issue where even after `verifyInformation` ran `zealotCount`, `summoningEyes`, and `sinceLastEye` kept their default values making them reset to 0 after the game was restarted. My fix was to set the values based on `zealotData` at the end of `verifyInformation` but I wasn't really thinking when I did that.

### CODE REVIEW

**Comment by symt** [comment]
I'm going to go out on a limb and say this breaks when a player deletes (or otherwise is removed from) a profile. This is just an issue with the mod, not with the PR in particular. Do you have any ideas on how to handle that?

**Comment by ghost** [comment]
Similar to how profile names are sent when you create one or connect to skyblock with more than one profile already, the profile name is shown in chat. The deletion message looks like this: "Done! Your 'profile name' profile was deleted!" However I'm not sure what (if anything) is sent when your kicked from a coop. Ideally a message is sent with the profile name you were kicked from. This kick message and the deletion message could call a method that deletes the data associated with that profile, or maybe prompts the user on what should be done with it.

**Comment by symt** [comment]
> Similar to how profile names are sent when you create one or connect to skyblock with more than one profile already, the profile name is shown in chat. The deletion message looks like this: "Done! Your 'profile name' profile was deleted!" However I'm not sure what (if anything) is sent when your kicked from a coop. Ideally a message is sent with the profile name you were kicked from. This kick message and the deletion message could call a method that deletes the data associated with that profile, or maybe prompts the user on what should be done with it.



That might work, but there is one problem: How do we know if they're down to one profile or not? You can't just say "if there is only one item left in zealotData" because there could be hidden profiles or profiles that the mod hasn't seen yet.

**Comment by ghost** [comment]
We can determine if a user is on a multi profile account by whether or not the message: "You are playing on profile: `profile name`" appears when they first log in. If a user deletes a profile we don't have data on, then they were on a multi profile account to begin with since when you create a profile your automatically switched to it. So in the case where someone installs the mod with multiple profiles, it doesn't matter if they delete all their other profiles right away since we have the profile name from when they first joined. So if this user logs in again and the message: "You are playing on `profile name`" doesn't appear, but we have data on a profile associated with their uuid, then isn't that profile the one they logged in on? I haven't been able to test what message (if any) appears when you are kicked from a coop so I can't guarantee that you will be able to know if a profile is lost this way. Another approach to this is hypixel's api. I haven't looked into it, but I'm pretty sure that any needed data can be gathered through it.

**Comment by symt** [comment]
Going to go ahead and merge this. I'll deal w/ deleting profiles in the future.

**Pull request merged**
