### PR TITLE
The mod now says the amount of zealots you killed for the eye when you get one

### PR DESCRIPTION
**Pull request by PerryPeak**
The mod now says the amount of zealots you killed for the eye when you get one. You can change the message's color by changing the constant in the ZealotCounter class.

### CODE REVIEW

**Comment by PerryPeak** [comment]
breaks the skyblock addons special zealot alert, need to either change event priority here or to make a pull request to skyblock addons

**Comment by symt** [comment]
I changed the base to 1.4.0 (the current update) and there are a few conflicts. Can you update your branch to deal w/ the changes?

Thanks for working on this.

**Review by symt — CHANGES_REQUESTED** [review]
See the comment above ^

**Comment by PerryPeak** [comment]
Gonna try to

**Comment by PerryPeak** [comment]
I am trying to make it work on 1.4.0 (had some problems because I don't use git a lot) but you are trying to get zealotCounter.lastSetup even that it doesn't exist (EventHandler line 107). You also did something similar in EventHandler line 112 but with a method

**Comment by symt** [comment]
> I am trying to make it work on 1.4.0 (had some problems because I don't use git a lot) but you are trying to get zealotCounter.lastSetup even that it doesn't exist (EventHandler line 107). You also did something similar in EventHandler line 112 but with a method

It should compile just fine by default. You could try remaking the branch and adding your changes manually to see if that fixes it. The branch should be made off 1.4.0, not master.

**Comment by PerryPeak** [comment]
ok I think it was just a mistake I made when merging, I am gonna test it and hope I don't lose a summoning eye because of it :P

**Comment by PerryPeak** [comment]
is the in game config menu supposed to work already? it doesn't work for me (1.4.0)

**Comment by symt** [comment]
> is the in game config menu supposed to work already? it doesn't work for me (1.4.0)

It should. What's wrong with it?

**Comment by PerryPeak** [comment]
One I think one of the problems was that it didn't import modcore (it didn't recognize the import) but it still happens every time I do /zc
(recording is in zip because github didn't let me upload mp4 and I was too lazy to upload to yt lol)

image

**Comment by PerryPeak** [comment]
didn't upload correctly
zc command gif

**Comment by PerryPeak** [comment]
I just found out it somehow breaks modcore instead of using it - it loads 0.1.16 even that 0.1.25 is released already and it doesn't work (probably the reason the gui didn't work). Can you send me a download link to your build of the mod? don't really wanna download the source code a few times and have a few versions of it

**Comment by symt** [comment]
I'm going to go ahead and close this. I'll put in the changes myself manually. Thank you for working on this.

**Comment by symt** [comment]
This would conflict with SkyblockAddons so I'm not going to mess w/ it just yet (going to work on a fix)

**Pull request closed without merging**
